apiVersion: apps/v1
kind: Deployment
metadata:
  name: dictionary-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: dictionary
  template:
    metadata:
      labels:
        app: dictionary
    spec:
      containers:
      - name: dictionary
        image: rameshkumarverma/dictionary
        ports:
        - containerPort: 80
