apiVersion: v1
kind: Service
metadata:
  name: wordictionary-service
spec:
  selector:
    app: wordictionary
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
